classdef Cell < edu.washington.riekelab.sources.Cell
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.addProperty('type', '', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'', 'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                    { ...
                        {}, ...
                        {}, ...
                        {'ON-parasol', 'OFF-parasol', 'ON-midget', 'OFF-midget', 'small bistratified'}, ...
                        {'AII', 'A17', 'starburst'}, ...
                        {'OFF-diffuse', 'OFF-midget', 'ON-diffuse', 'ON-midget', 'rod'}, ...
                        {}, ...
                        {'S cone', 'M cone', 'L cone', 'rod'} ...
                    })), ...
                'description', 'The confirmed type of the recorded cell', ...
                'isPreferred', true);
            
            obj.addAllowableParentType('edu.washington.riekelab.sources.primate.Preparation');
        end
        
    end
    
end

