classdef ZebrafishCell < edu.washington.rieke.sources.Cell
    
    methods
        
        function obj = ZebrafishCell()
            import symphonyui.core.*;
            
            obj.addProperty('type', '[>, unknown]', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                    {{}, ...
                    {}, ...
                    {}, ...
                    {'VSX1', 'VSX2'}, ...
                    {}, ...
                    {'UV cone', 'S cone', 'M cone', 'rod'}})), ...
                'description', 'The confirmed type of the recorded cell');
        end
        
    end
    
end

