classdef Standard < symphonyui.core.descriptions.EpochGroupDescription
    
    methods
        
        function obj = Standard()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('externalSolutionAdditions', {}, ...
                    'type', PropertyType('cellstr', 'row', {'NBQX (10uM)', 'DAPV (50uM)', 'APB (10uM)', 'LY 341495 (10uM)', 'strychnine (0.5uM)', 'strychnine (25uM)', 'gabazine (10uM)', 'gabazine (25uM)', 'TPMPA (50uM)', 'TTX (100nM)', 'TTX (500nM)'})), ...
                PropertyDescriptor('pipetteSolution', '', ...
                    'type', PropertyType('char', 'row', {'', 'cesium', 'potassium', 'potassium zero calcium buffer', 'full chloride cesium', 'Ames'})), ...
                PropertyDescriptor('internalSolutionAdditions', ''), ...
                PropertyDescriptor('recordingTechnique', '', ...
                    'type', PropertyType('char', 'row', {'', 'cell-attached', 'whole-cell', 'perforated patch', 'suction'})), ...
                PropertyDescriptor('seriesResistanceCompensation', int32(0), ...
                    'type', PropertyType('int32', 'scalar', [0 100])), ...
                ];
        end
        
    end
    
end

