classdef (Abstract) Preparation < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Preparation()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('time', datestr(now), ...
                    'type', PropertyType('char', 'row', 'datestr'), ...
                    'description', 'Time the preparation was prepared'), ...
                PropertyDescriptor('region', {}, ...
                    'type', PropertyType('cellstr', 'row', {'fovea', 'parafovea', 'peripheral', 'temporal', 'nasal', 'dorsal', 'ventral'})), ...
                PropertyDescriptor('preparation', '', ...
                    'type', PropertyType('char', 'row', {'', 'shredded retina', 'whole mount, cones up', 'whole mount, RGCs up', 'slice'})), ...
                PropertyDescriptor('bathSolution', '', ...
                    'type', PropertyType('char', 'row', {'', 'Ames'}), ...
                    'description', 'The solution the preparation is bathed in'), ...
                ];            
        end
        
    end
    
end

