classdef (Abstract) Subject < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Subject()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('id', '', ...
                    'description', 'ID of animal/person (lab convention)'), ...
                PropertyDescriptor('description', '', ...
                    'description', 'Description of subject and where subject came from (eg, breeder, if animal)'), ...
                PropertyDescriptor('sex', '', ...
                    'type', PropertyType('char', 'row', {'', 'male', 'female'}), ...
                    'description', 'Gender of the subject'), ...
                PropertyDescriptor('age', '', ...
                    'description', 'Age of person, animal, embryo'), ...
                PropertyDescriptor('weight', '', ...
                    'description', 'Weight at time of experiment, at time of surgery, and at other important times'), ...
                PropertyDescriptor('darkAdaptation', '', ...
                    'type', PropertyType('char', 'row', {'', 'overnight', '1 hour', '2 hours'}), ...
                    'description', 'Period of time the subject was allowed to adjust to the dark'), ...
                ];            
        end
        
    end
    
end

