classdef MouseCell < edu.washington.rieke.sources.Cell
    
    methods
        
        function obj = MouseCell()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                obj.propertyDescriptors, ...
                PropertyDescriptor('type', '[>, unknown]', ...
                    'type', PropertyType('char', 'row', containers.Map( ...
                        {'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                        {{}, ...
                        {'ON-alpha', 'ON-transient', 'OFF-transient', 'OFF-sustained', 'ON/OFF DS', 'ON DS', 'W3/local edge detector'}, ...
                        {'AII', 'A17', 'starburst', 'AC5170'}, ...
                        {'rod bipolar', 'cone bipolar'}, ...
                        {}, ...
                        {'S cone', 'M cone', 'rod'}})), ...
                    'description', 'The confirmed type of the recorded cell'), ...
                    ];
        end
        
    end
    
end

