classdef PrimateCell < edu.washington.rieke.sources.Cell
    
    methods
        
        function obj = PrimateCell()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                obj.propertyDescriptors, ...
                PropertyDescriptor('type', '[>, unknown]', ...
                    'type', PropertyType('char', 'row', containers.Map( ...
                        {'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                        {{}, ...
                        {'ON-parasol', 'OFF-parasol', 'ON-midget', 'OFF-midget', 'small bistratified'}, ...
                        {'AII', 'A17', 'starburst'}, ...
                        {'OFF-diffuse', 'OFF-midget', 'ON-diffuse', 'ON-midget', 'rod'}, ...
                        {}, ...
                        {'S cone', 'M cone', 'L cone', 'rod'}})), ...
                    'description', 'The confirmed type of the recorded cell'), ...
                    ];
        end
        
    end
    
end

